# Generated by Django 4.1.1 on 2022-09-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_taskslist_title_alter_taskslist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Сделано')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
