# Generated by Django 4.1.1 on 2022-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_taskslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='title',
            field=models.TextField(max_length=1000, verbose_name='Задача'),
        ),
    ]
